-- UV 포털 — 프로그램 목록·판·회원 자격 (2026-09-14, 설계: uv-global-reaction-editor/docs/superpowers/specs/2026-09-14-uv-portal-design.md)
-- 적용: Supabase 대시보드 SQL 편집기 또는 관리 API POST /database/query (postgres 역할). 여러 번 실행해도 안전하다.
-- 관리자 판정은 raion-admin 이 쓰는 private.is_admin() 을 그대로 쓴다 — 포털이 관리자 명단을 따로 두지 않는다.
-- 편집기 수강생 자격은 앱 관문이 보는 public.uvengers_editor_members(id = auth.users.id, status, valid_until) 를 그대로 본다.

begin;

create table if not exists public.uvengers_programs (
  code        text primary key,                       -- 저장소 이름 그대로: uv-global-reaction-editor
  name        text not null,                          -- 화면 이름: UV 글로벌 반응 편집기
  tagline     text,                                   -- 한 줄 소개
  guide_url   text,                                   -- 설치·사용 안내
  landing_url text,                                   -- 공개 소개 페이지(있으면)
  sort        integer not null default 100,
  active      boolean not null default true,
  created_at  timestamptz not null default now()
);

create table if not exists public.uvengers_releases (
  id            bigint generated by default as identity primary key,
  program_code  text not null references public.uvengers_programs(code) on delete cascade,
  version       text not null,                        -- 1.3.3
  tag           text not null,                        -- v1.3.3-rc.6
  file_name     text not null,                        -- UV-Global-Reaction-Editor_1.3.3_x64-setup.exe
  bytes         bigint not null,
  sha256        text not null,
  download_url  text not null,
  notes_url     text,                                 -- GitHub 릴리스 페이지
  published_at  timestamptz not null,
  is_prerelease boolean not null default true,
  created_by    uuid default auth.uid(),
  created_at    timestamptz not null default now(),
  unique (program_code, tag)
);
-- 바뀐 점 두 줄 요약 — 수강생 카드에 그대로 보인다(사용자 2026-09-14 「바뀐 점도 2줄 정도는 써줘」). 이미 있는 표에도 더한다.
alter table public.uvengers_releases add column if not exists notes text;

-- 앞으로 생길 프로그램의 수강생 자격(편집기는 기존 표를 쓴다)
create table if not exists public.uvengers_program_members (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references auth.users(id) on delete cascade,
  program_code  text not null references public.uvengers_programs(code) on delete cascade,
  status        text not null default 'approved',     -- approved | suspended | withdrawn
  valid_until   timestamptz,
  note          text,
  created_at    timestamptz not null default now(),
  unique (user_id, program_code)
);

-- ── 판정 함수 ─────────────────────────────────────────────────────────────────
create or replace function public.portal_is_admin()
returns boolean language sql stable security definer set search_path = public, private as $$
  select coalesce(private.is_admin(), false);
$$;

create or replace function public.portal_can_see(p_code text)
returns boolean language sql stable security definer set search_path = public, private as $$
  select public.portal_is_admin()
      or (p_code = 'uv-global-reaction-editor' and exists (
            select 1 from public.uvengers_editor_members e
             where e.id = auth.uid()
               and lower(coalesce(e.status, '')) in ('approved', 'active')
               and (e.valid_until is null or e.valid_until >= now())))
      or exists (
            select 1 from public.uvengers_program_members m
             where m.user_id = auth.uid() and m.program_code = p_code
               and lower(m.status) in ('approved', 'active')
               and (m.valid_until is null or m.valid_until >= now()));
$$;

-- 로그인한 사람의 역할과 자격을 한 번에 — 화면은 이 답만 믿는다
create or replace function public.portal_me()
returns jsonb language sql stable security definer set search_path = public, private as $$
  select jsonb_build_object(
    'user_id', auth.uid(),
    'email', auth.jwt() ->> 'email',
    'is_admin', public.portal_is_admin(),
    'memberships', coalesce((
      select jsonb_agg(x) from (
        select 'uv-global-reaction-editor' as program_code, e.status, e.valid_until
          from public.uvengers_editor_members e where e.id = auth.uid()
        union all
        select m.program_code, m.status, m.valid_until
          from public.uvengers_program_members m where m.user_id = auth.uid()
      ) x), '[]'::jsonb)
  );
$$;

revoke all on function public.portal_is_admin() from public;
revoke all on function public.portal_can_see(text) from public;
revoke all on function public.portal_me() from public;
grant execute on function public.portal_is_admin() to authenticated;
grant execute on function public.portal_can_see(text) to authenticated;
grant execute on function public.portal_me() to authenticated;
revoke execute on function public.portal_is_admin(), public.portal_can_see(text), public.portal_me() from anon; -- 기본 권한이 anon 에게도 execute 를 준다(실측 2026-09-14: anon 이 portal_me 200) — 명시적으로 회수

-- ── RLS ───────────────────────────────────────────────────────────────────────
alter table public.uvengers_programs        enable row level security;
alter table public.uvengers_releases        enable row level security;
alter table public.uvengers_program_members enable row level security;

drop policy if exists programs_read  on public.uvengers_programs;
drop policy if exists programs_admin on public.uvengers_programs;
create policy programs_read  on public.uvengers_programs for select to authenticated using (public.portal_can_see(code));
create policy programs_admin on public.uvengers_programs for all    to authenticated
  using (public.portal_is_admin()) with check (public.portal_is_admin());

drop policy if exists releases_read  on public.uvengers_releases;
drop policy if exists releases_admin on public.uvengers_releases;
create policy releases_read  on public.uvengers_releases for select to authenticated using (public.portal_can_see(program_code));
create policy releases_admin on public.uvengers_releases for all    to authenticated
  using (public.portal_is_admin()) with check (public.portal_is_admin());

drop policy if exists members_self  on public.uvengers_program_members;
drop policy if exists members_admin on public.uvengers_program_members;
create policy members_self  on public.uvengers_program_members for select to authenticated using (user_id = auth.uid());
create policy members_admin on public.uvengers_program_members for all    to authenticated
  using (public.portal_is_admin()) with check (public.portal_is_admin());

grant select, insert, update, delete on public.uvengers_programs, public.uvengers_releases, public.uvengers_program_members to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- ── 첫 데이터: 반응 편집기와 지금 배포된 판 ─────────────────────────────────────
insert into public.uvengers_programs (code, name, tagline, guide_url, landing_url, sort)
values ('uv-global-reaction-editor', 'UV 글로벌 반응 편집기',
        'YouTube 반응 영상을 국가별 자긍심 콘텐츠로 재구성하는 Windows 편집기',
        'https://raion-log.github.io/uv-global-reaction-editor-releases/',
        'https://raion-log.github.io/uv-global-reaction-editor-releases/', 10)
on conflict (code) do update set name = excluded.name, tagline = excluded.tagline;

insert into public.uvengers_releases (program_code, version, tag, file_name, bytes, sha256, download_url, notes_url, published_at, is_prerelease)
values ('uv-global-reaction-editor', '1.3.3', 'v1.3.3-rc.6', 'UV-Global-Reaction-Editor_1.3.3_x64-setup.exe', 670338555,
        'fe28374388f3f4acc5fbb23ac1f4e9263d4da6162b4faa5bd9a288681cf70ed0',
        'https://github.com/raion-log/uv-global-reaction-editor-releases/releases/download/v1.3.3-rc.6/UV-Global-Reaction-Editor_1.3.3_x64-setup.exe',
        'https://github.com/raion-log/uv-global-reaction-editor-releases/releases/tag/v1.3.3-rc.6',
        '2026-09-13 19:10:00+09', true),
       ('uv-global-reaction-editor', '1.3.0', 'v1.3.0', 'UV-Global-Reaction-Editor_1.3.0_x64-setup.exe', 670156588,
        '47249cd54a996ef6639a5d71a06cafdb2bd56313c4b2592a3d38eb481492c3d2',
        'https://github.com/raion-log/uv-global-reaction-editor-releases/releases/download/v1.3.0/UV-Global-Reaction-Editor_1.3.0_x64-setup.exe',
        'https://github.com/raion-log/uv-global-reaction-editor-releases/releases/tag/v1.3.0',
        '2026-09-09 01:09:46+09', false)
on conflict (program_code, tag) do nothing;

-- 첫 두 판의 바뀐 점(CHANGELOG 요약). 비어 있을 때만 채운다 — 관리자가 고친 글을 덮지 않는다.
update public.uvengers_releases set notes = E'AI 응답이 멈춰도 전체가 멈추지 않고, 자료 화면이 이야기와 맞습니다(다른 나라 이야기에 한국 화면이 오지 않음).\n나레이션 분량이 레퍼런스 수준으로, 일본어·번체 발음 사전, 설정에 「내 계정」 탭, 진행 화면 썸네일 후보가 오른쪽 열에.'
 where program_code = 'uv-global-reaction-editor' and tag = 'v1.3.3-rc.6' and notes is null;
update public.uvengers_releases set notes = E'자막이 막혀도 소리로 직접 재서 분량을 정하고, 원본 소리에서 음악·효과음을 빼 목소리만 남깁니다.\n나레이션이 레퍼런스만큼(분당 140자) 들어갑니다.'
 where program_code = 'uv-global-reaction-editor' and tag = 'v1.3.0' and notes is null;

commit;

-- REST(PostgREST) 스키마 캐시 새로고침 — 없으면 새 표·함수가 REST 에서 404 (실측 2026-09-14)
notify pgrst, 'reload schema';
