-- UV 포털 — 프로그램 목록·판·회원 자격 (2026-09-14, 설계: uv-global-reaction-editor/docs/superpowers/specs/2026-09-14-uv-portal-design.md)
-- 적용: Supabase 대시보드 SQL 편집기 또는 관리 API POST /database/query (postgres 역할). 여러 번 실행해도 안전하다.
-- 관리자 판정은 raion-admin 이 쓰는 private.is_admin() 을 그대로 쓴다 — 포털이 관리자 명단을 따로 두지 않는다.
-- 편집기 수강생 자격은 앱 관문이 보는 public.uvengers_editor_members(id = auth.users.id, status, valid_until) 를 그대로 본다.

begin;

create table if not exists public.uvengers_programs (
  code        text primary key,                       -- 저장소 이름 그대로: uv-global-reaction-editor
  name        text not null,                          -- 화면 이름: UV 글로벌 반응 편집기
  tagline     text,                                   -- 한 줄 소개
  guide_url   text,                                   -- 설치·사용 안내
  landing_url text,                                   -- 공개 소개 페이지(있으면)
  sort        integer not null default 100,
  active      boolean not null default true,
  created_at  timestamptz not null default now()
);

create table if not exists public.uvengers_releases (
  id            bigint generated by default as identity primary key,
  program_code  text not null references public.uvengers_programs(code) on delete cascade,
  version       text not null,                        -- 1.3.3
  tag           text not null,                        -- v1.3.3-rc.6
  file_name     text not null,                        -- UV-Global-Reaction-Editor_1.3.3_x64-setup.exe
  bytes         bigint not null,
  sha256        text not null,
  download_url  text not null,
  notes_url     text,                                 -- GitHub 릴리스 페이지
  published_at  timestamptz not null,
  is_prerelease boolean not null default true,
  created_by    uuid default auth.uid(),
  created_at    timestamptz not null default now(),
  unique (program_code, tag)
);
-- 바뀐 점 두 줄 요약 — 수강생 카드에 그대로 보인다(사용자 2026-09-14 「바뀐 점도 2줄 정도는 써줘」). 이미 있는 표에도 더한다.
alter table public.uvengers_releases add column if not exists notes text;

-- 앞으로 생길 프로그램의 수강생 자격(편집기는 기존 표를 쓴다)
create table if not exists public.uvengers_program_members (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references auth.users(id) on delete cascade,
  program_code  text not null references public.uvengers_programs(code) on delete cascade,
  status        text not null default 'approved',     -- approved | suspended | withdrawn
  valid_until   timestamptz,
  note          text,
  created_at    timestamptz not null default now(),
  unique (user_id, program_code)
);

-- ── 기수 × 프로그램 — 허브(raion-log/uv 의 courses.js·products/*.js 의 courses)를 그대로 가져온 것 ────────
--    사용자 2026-09-14: 「이전에 정리했던 곳에 다 정리되어있으니까 그거 갖고 와서 여기에 정리… 관리자한테만 보여지게」.
--    기수에 프로그램을 켜면 그 기수 회원(uvengers_members.batch / uvengers_editor_members.cohort) 전원에게 보인다.
--    ★반응 편집기는 예외 — 앱의 가입·승인·이용 기한(uvengers_editor_members)이 우선이고 기수 체크는 표시용이다.
create table if not exists public.uvengers_cohorts (
  name        text primary key,                       -- '유벤져스 1기' — 회원 표의 batch/cohort 와 글자가 같아야 한다
  sort        int  not null default 100,
  created_at  timestamptz not null default now()
);
create table if not exists public.uvengers_program_cohorts (
  program_code text not null references public.uvengers_programs(code) on delete cascade,
  cohort       text not null references public.uvengers_cohorts(name)  on delete cascade,
  created_at   timestamptz not null default now(),
  primary key (program_code, cohort)
);

-- ── 판정 함수 ─────────────────────────────────────────────────────────────────
create or replace function public.portal_is_admin()
returns boolean language sql stable security definer set search_path = public, private as $$
  select coalesce(private.is_admin(), false);
$$;

-- 로그인한 사람의 기수 — 관리 표(uvengers_members.batch, 관리자만 쓴다)만 본다.
-- ★편집기 표의 cohort 는 가입 때 본인이 고르는 값이라 자격 근거로 쓰지 않는다(적대평가 2026-09-14: 미승인 가입자가 기수를
--   골라 다른 프로그램을 열 수 있었다). 상태도 활동 중인 회원만.
create or replace function public.portal_my_cohorts()
returns setof text language sql stable security definer set search_path = public, private as $$
  select m.batch from public.uvengers_members m
   where lower(m.email) = lower(auth.jwt() ->> 'email')
     and m.batch is not null
     and lower(coalesce(m.status, '')) in ('active', 'approved');
$$;

create or replace function public.portal_can_see(p_code text)
returns boolean language sql stable security definer set search_path = public, private as $$
  select public.portal_is_admin()
      -- 편집기: 앱 관문(uvengers_editor_access_check)과 같은 판정 — valid_until 이 NULL 이면 미승인이다
      -- ★승인 대기(pending)도 연다(사용자 2026-09-15 「둘 다 허용」): 사이트는 승인돼야 설치기를 주고 앱은 받아야 가입하던
      --   닭·달걀을 푼다. 설치기를 받아도 앱 관문이 승인 전엔 안 연다. 차단·거절은 그대로 막는다.
      or (p_code = 'uv-global-reaction-editor' and exists (
            select 1 from public.uvengers_editor_members e
             where e.id = auth.uid()
               and ((lower(coalesce(e.status, '')) in ('approved', 'active')
                     and e.valid_until is not null and e.valid_until >= now())
                    or lower(coalesce(e.status, '')) = 'pending')))
      or exists (
            select 1 from public.uvengers_program_members m
             where m.user_id = auth.uid() and m.program_code = p_code
               and lower(m.status) in ('approved', 'active')
               and (m.valid_until is null or m.valid_until >= now()))
      or (p_code <> 'uv-global-reaction-editor' and exists (
            select 1 from public.uvengers_program_cohorts pc
             where pc.program_code = p_code
               and pc.cohort in (select public.portal_my_cohorts())));
$$;

-- 로그인한 사람의 역할과 자격을 한 번에 — 화면은 이 답만 믿는다
create or replace function public.portal_me()
returns jsonb language sql stable security definer set search_path = public, private as $$
  select jsonb_build_object(
    'user_id', auth.uid(),
    'email', auth.jwt() ->> 'email',
    'is_admin', public.portal_is_admin(),
    'cohorts', coalesce((select jsonb_agg(c) from public.portal_my_cohorts() c), '[]'::jsonb),
    'memberships', coalesce((
      select jsonb_agg(x) from (
        select 'uv-global-reaction-editor' as program_code, e.status, e.valid_until, 'editor' as via, null::text as cohort
          from public.uvengers_editor_members e where e.id = auth.uid()
        union all
        select m.program_code, m.status, m.valid_until, 'member' as via, null::text as cohort
          from public.uvengers_program_members m where m.user_id = auth.uid()
        union all
        select pc.program_code, 'approved' as status, null::timestamptz as valid_until, 'cohort' as via, pc.cohort
          from public.uvengers_program_cohorts pc
         where pc.program_code <> 'uv-global-reaction-editor'
           and pc.cohort in (select public.portal_my_cohorts())
      ) x), '[]'::jsonb)
  );
$$;

-- 공개(anon 허용) 둘: 릴리스 검증이 「포털 최신 판이 이번 판인가」를 묻는 함수(판·태그만, 링크 없음),
-- 가입 화면의 기수 선택 목록(편집기 앱의 uvengers_editor_cohorts 활성 이름). 둘 다 공개돼도 되는 정보다.
create or replace function public.portal_latest_public(p_code text)
returns table (version text, tag text, published_at timestamptz, is_prerelease boolean)
language sql stable security definer set search_path = public as $$
  select r.version, r.tag, r.published_at, r.is_prerelease
    from public.uvengers_releases r
   where r.program_code = p_code
   order by r.published_at desc, r.id desc
   limit 1;
$$;
create or replace function public.portal_signup_cohorts()
returns table (name text) language sql stable security definer set search_path = public as $$
  select c.name from public.uvengers_editor_cohorts c where c.active = true order by c.name;
$$;
revoke all on function public.portal_latest_public(text) from public;
revoke all on function public.portal_signup_cohorts() from public;
grant execute on function public.portal_latest_public(text) to anon, authenticated;
grant execute on function public.portal_signup_cohorts() to anon, authenticated;

-- 관리자용: 기수 목록과 회원 수(두 회원 표의 이메일을 합쳐 센다)
create or replace function public.portal_cohorts()
returns table (name text, sort int, members bigint) language sql stable security definer set search_path = public, private as $$
  select c.name, c.sort,
         (select count(distinct u.email) from (
            select m.email from public.uvengers_members m where m.batch = c.name
            union
            select e.email from public.uvengers_editor_members e where e.cohort = c.name) u) as members
    from public.uvengers_cohorts c
   where public.portal_is_admin()
   order by c.sort, c.name;
$$;

revoke all on function public.portal_is_admin() from public;
revoke all on function public.portal_can_see(text) from public;
revoke all on function public.portal_me() from public;
revoke all on function public.portal_my_cohorts() from public;
revoke all on function public.portal_cohorts() from public;
grant execute on function public.portal_is_admin() to authenticated;
grant execute on function public.portal_can_see(text) to authenticated;
grant execute on function public.portal_me() to authenticated;
grant execute on function public.portal_my_cohorts() to authenticated;
grant execute on function public.portal_cohorts() to authenticated;
revoke execute on function public.portal_is_admin(), public.portal_can_see(text), public.portal_me(), public.portal_my_cohorts(), public.portal_cohorts() from anon; -- 기본 권한이 anon 에게도 execute 를 준다(실측 2026-09-14: anon 이 portal_me 200) — 명시적으로 회수

-- ── RLS ───────────────────────────────────────────────────────────────────────
alter table public.uvengers_programs        enable row level security;
alter table public.uvengers_releases        enable row level security;
alter table public.uvengers_program_members enable row level security;

drop policy if exists programs_read  on public.uvengers_programs;
drop policy if exists programs_admin on public.uvengers_programs;
create policy programs_read  on public.uvengers_programs for select to authenticated using (public.portal_can_see(code));
create policy programs_admin on public.uvengers_programs for all    to authenticated
  using (public.portal_is_admin()) with check (public.portal_is_admin());

drop policy if exists releases_read  on public.uvengers_releases;
drop policy if exists releases_admin on public.uvengers_releases;
create policy releases_read  on public.uvengers_releases for select to authenticated using (public.portal_can_see(program_code));
create policy releases_admin on public.uvengers_releases for all    to authenticated
  using (public.portal_is_admin()) with check (public.portal_is_admin());

drop policy if exists members_self  on public.uvengers_program_members;
drop policy if exists members_admin on public.uvengers_program_members;
create policy members_self  on public.uvengers_program_members for select to authenticated using (user_id = auth.uid());
create policy members_admin on public.uvengers_program_members for all    to authenticated
  using (public.portal_is_admin()) with check (public.portal_is_admin());

alter table public.uvengers_cohorts         enable row level security;
alter table public.uvengers_program_cohorts enable row level security;
drop policy if exists cohorts_admin on public.uvengers_cohorts;
drop policy if exists program_cohorts_admin on public.uvengers_program_cohorts;
create policy cohorts_admin on public.uvengers_cohorts for all to authenticated
  using (public.portal_is_admin()) with check (public.portal_is_admin());
create policy program_cohorts_admin on public.uvengers_program_cohorts for all to authenticated
  using (public.portal_is_admin()) with check (public.portal_is_admin());

grant select, insert, update, delete on public.uvengers_programs, public.uvengers_releases, public.uvengers_program_members,
  public.uvengers_cohorts, public.uvengers_program_cohorts to authenticated;
-- 포털 표의 id 시퀀스만(public 전체 시퀀스에 주면 다른 제품 표까지 열린다 — 적대평가 2026-09-14)
grant usage, select on sequence public.uvengers_releases_id_seq, public.uvengers_program_members_id_seq to authenticated;
-- anon 은 표를 만질 이유가 없다. RLS 정책이 authenticated 전용이라 0행이긴 하지만(실측 200 []), 기본 권한으로 받은 표 권한은 회수한다(적대평가 2026-09-14).
revoke all on public.uvengers_programs, public.uvengers_releases, public.uvengers_program_members,
  public.uvengers_cohorts, public.uvengers_program_cohorts from anon;

-- ── 첫 데이터: 반응 편집기와 지금 배포된 판 ─────────────────────────────────────
insert into public.uvengers_programs (code, name, tagline, guide_url, landing_url, sort)
values ('uv-global-reaction-editor', 'UV 글로벌 반응 편집기',
        'YouTube 반응 영상을 국가별 자긍심 콘텐츠로 재구성하는 Windows 편집기',
        'https://raion-log.github.io/uv-global-reaction-editor-releases/',
        'https://raion-log.github.io/uv-global-reaction-editor-releases/', 10)
on conflict (code) do nothing;   -- 관리자가 고친 이름·소개를 재적용이 되돌리지 않는다(적대평가 2026-09-14)

insert into public.uvengers_releases (program_code, version, tag, file_name, bytes, sha256, download_url, notes_url, published_at, is_prerelease)
values ('uv-global-reaction-editor', '1.3.3', 'v1.3.3-rc.6', 'UV-Global-Reaction-Editor_1.3.3_x64-setup.exe', 670338555,
        'fe28374388f3f4acc5fbb23ac1f4e9263d4da6162b4faa5bd9a288681cf70ed0',
        'https://github.com/raion-log/uv-global-reaction-editor-releases/releases/download/v1.3.3-rc.6/UV-Global-Reaction-Editor_1.3.3_x64-setup.exe',
        'https://github.com/raion-log/uv-global-reaction-editor-releases/releases/tag/v1.3.3-rc.6',
        '2026-09-13 19:10:00+09', true),
       ('uv-global-reaction-editor', '1.3.0', 'v1.3.0', 'UV-Global-Reaction-Editor_1.3.0_x64-setup.exe', 670156588,
        '47249cd54a996ef6639a5d71a06cafdb2bd56313c4b2592a3d38eb481492c3d2',
        'https://github.com/raion-log/uv-global-reaction-editor-releases/releases/download/v1.3.0/UV-Global-Reaction-Editor_1.3.0_x64-setup.exe',
        'https://github.com/raion-log/uv-global-reaction-editor-releases/releases/tag/v1.3.0',
        '2026-09-09 01:09:46+09', false)
on conflict (program_code, tag) do nothing;

-- 첫 두 판의 바뀐 점(CHANGELOG 요약). 비어 있을 때만 채운다 — 관리자가 고친 글을 덮지 않는다.
-- 허브(raion-log/uv)의 나머지 프로그램 — products/*.js 의 id·name·desc 그대로. 판(파일·크기·해시)은 아래 릴리스 씨앗에.
insert into public.uvengers_programs (code, name, tagline, guide_url, landing_url, sort)
values ('flow',             'RAION Flow Pro',     'Google Flow 에서 이미지·영상 만드는 일을 반자동으로 도와주는 크롬 확장프로그램', 'https://raion-log.github.io/uv/guide/flow/', null, 20),
       ('genspark',         'RAION Genspark Pro', 'Genspark 에서 이미지·영상 만드는 일을 반자동으로 도와주는 크롬 확장프로그램', null, null, 30),
       ('grok',             'RAION Grok Pro',     'Grok 에서 이미지·영상 만드는 일을 반자동으로 도와주는 크롬 확장프로그램', null, null, 40),
       ('vrewauto-classic', 'VrewAuto 자동배치 · 브루만 있는 버전', 'Vrew(브루) 씬별로 이미지를 자동 배치합니다. 캡컷 기능은 들어 있지 않습니다.', 'https://raion-log.github.io/vrewauto-releases/', null, 50),
       ('vrewauto-new',     'VrewAuto 자동배치 · 캡컷 포함 버전',   'Vrew(브루) 씬별 이미지 자동 배치에 더해 캡컷 초안 정리까지 해 줍니다.', 'https://raion-log.github.io/vrewauto-releases/with-capcut/', null, 60)
on conflict (code) do nothing;

-- 허브 프로그램의 현재 판 — 크기는 GitHub 릴리스 자산 값, SHA-256 은 실제로 내려받아 잰 값(2026-09-14).
-- VrewAuto 브루만 있는 버전(2.0.8)은 GitHub 릴리스에 자산이 없어 판을 넣지 않는다(허브도 설치 가이드로만 안내).
insert into public.uvengers_releases (program_code, version, tag, file_name, bytes, sha256, download_url, notes_url, published_at, is_prerelease)
values ('flow', '1.2.2', 'v1.2.2', 'raion-flow-pro-v1.2.2.zip', 2455477,
        'eb25c842f42c6f1642b2b335f0dfa865661402ebd8631be2c152af6da5b6e898',
        'https://github.com/raion-log/raion-flow-pro-release/releases/download/v1.2.2/raion-flow-pro-v1.2.2.zip',
        'https://github.com/raion-log/raion-flow-pro-release/releases', '2026-05-22 00:00:00+09', false),
       ('genspark', '1.0.6', 'v1.0.6', 'dist.zip', 2657173,
        'a9b436eacadc62075c5abafdca1befa8a23b13ba731c454781274c65621e1761',
        'https://github.com/raion-log/raion-genspark-pro-releases/releases/download/v1.0.6/dist.zip',
        'https://github.com/raion-log/raion-genspark-pro-releases/releases', '2026-05-20 00:00:00+09', false),
       ('grok', '8.8.6', 'v8.8.6', 'dist.zip', 3303915,
        '1c70126416fb36d356c9a1185e1e34704d11e9fb101eb47219209048000493d2',
        'https://github.com/raion-log/raion-grok-pro-releases/releases/download/v8.8.6/dist.zip',
        'https://github.com/raion-log/raion-grok-pro-releases/releases', '2026-08-30 00:00:00+09', false),
       ('vrewauto-new', '2.1.2', 'v2.1.2', 'VrewAuto_2.1.2_x64-setup.exe', 198651664,
        '5163629f148044576095fca7d09474acccbfc518b806ae29f4f6aa4f82f9408a',
        'https://github.com/raion-log/vrewauto-releases/releases/download/v2.1.2/VrewAuto_2.1.2_x64-setup.exe',
        'https://github.com/raion-log/vrewauto-releases/releases', '2026-09-12 10:27:26+09', true)
on conflict (program_code, tag) do nothing;

-- 기수(허브 courses.js 순서) 와 기수 × 프로그램(허브 products/*.js 의 courses)
insert into public.uvengers_cohorts (name, sort)
values ('빈이파파 1기', 10), ('빈이파파 2기', 20), ('빈이파파 3기', 30), ('라이온 1기', 40), ('애삼이 1기', 50),
       ('유벤져스 1기', 60), ('유벤져스 2기', 70), ('유유스 1기', 80)
on conflict (name) do nothing;
-- ★표가 비어 있을 때만(처음 켤 때만) 넣는다 — 관리자가 화면에서 끈 칸을 재적용이 되살리면 안 된다(적대평가 2026-09-14).
insert into public.uvengers_program_cohorts (program_code, cohort)
select v.program_code, v.cohort from (values
       ('flow', '빈이파파 1기'), ('flow', '빈이파파 2기'), ('flow', '라이온 1기'), ('flow', '애삼이 1기'),
       ('genspark', '빈이파파 1기'), ('genspark', '빈이파파 2기'), ('genspark', '라이온 1기'), ('genspark', '애삼이 1기'),
       ('grok', '빈이파파 1기'), ('grok', '빈이파파 2기'), ('grok', '라이온 1기'), ('grok', '애삼이 1기'),
       ('vrewauto-classic', '빈이파파 2기'),
       ('vrewauto-new', '빈이파파 3기'),
       ('uv-global-reaction-editor', '유유스 1기')) as v(program_code, cohort)
 where not exists (select 1 from public.uvengers_program_cohorts)
on conflict do nothing;

-- 줄마다 한 항목(카드에 목록으로 보인다).
update public.uvengers_releases set notes = E'AI 응답이 멈춰도 전체가 멈추지 않음\n다른 나라 이야기에 한국 자료 화면이 오지 않음\n나레이션 분량 레퍼런스 수준, 일본어·번체 발음 사전\n설정 「내 계정」 탭, 진행 화면 썸네일 후보 오른쪽 열'
 where program_code = 'uv-global-reaction-editor' and tag = 'v1.3.3-rc.6' and notes is null;
update public.uvengers_releases set notes = E'자막이 막혀도 소리로 직접 재서 분량을 정함\n원본 소리에서 음악·효과음을 빼고 목소리만\n나레이션 분당 90자 → 140자'
 where program_code = 'uv-global-reaction-editor' and tag = 'v1.3.0' and notes is null;

commit;

-- REST(PostgREST) 스키마 캐시 새로고침 — 없으면 새 표·함수가 REST 에서 404 (실측 2026-09-14)
notify pgrst, 'reload schema';
